### ISSUE TITLE
CNI Installer migration

### ISSUE THREAD

**Issue by rbtr** [Azure/azure-container-networking#2333]
This is a tracking issue for the work to migrate from the single `dropgz` image to per-component `-installer` images.

Up until now, we have released the CNI installer image (`cni-dropgz`) as a versioned component separately from the CNI releases themselves. This has created a bit of versioning hell, as we struggle to maintain multiple release trains of the CNI (and thus CNI installer) and azure-ipam when the CNI/azure-ipam and installer version are not correlated. 

The proposed change is to flip the architecture of the CNI installer: treat `dropgz` as a library, and leverage it to build separate installer images for each versioned component which we need to install via container. 

We will migrate from the current state of:

|image|binaries|version|
|-|-|-|
|cni-dropgz||a.b.c|
||azure-vnet|j.k.l|
||azure-ipam|x.y.z|

to 
|image|binaries|version|
|-|-|-|
|cni-installer||j.k.l|
||azure-vnet|j.k.l|
|ipam-installer||x.y.z|
||azure-ipam|x.y.z|

Migration steps:
- [x] ~Build CNI installer images~ #2324
- [x] ~Build azure-ipam installer images~ #2339 
- [x] ~Set up MCR publishing on new images~ MCR #2917
- [x] ~Add MCR sovcloud syndication~ MCR #3016
- [x] ~Migrate pipelines to new images~ #2372
- [x] ~Add v1 scenario installation daemonset to AKS~ AKS #9774675
- [x] Migrate existing downstreams to new images
  - [x] AgentBaker https://github.com/Azure/AgentBaker/pull/4256
  - [x] AKS
  - [x] ~CAPZ~ https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4315
- [x] Remove existing dropgz image infra (Dockerfiles, pipelines, etc) 
  - [x] ~dropgz-test images~ #2372
  - [x] dropgz images
- [x] Remove AzCNI bins from AgentBaker

**Comment by rbtr** [comment]
this is done for 1.5+, and can be closed as completed once #2871 is completed and AKS migrates for k8s 1.27.

**Comment by rbtr** [comment]
AKS has migrated and cni-dropgz is unused. Purging it from the VHD [here](https://github.com/Azure/AgentBaker/pull/5300) and closing this as complete 🎉
